### ISSUE TITLE
Is it work-in-progress?

### ISSUE THREAD

**Issue by JinraeKim** [MOCAP4ROS2-Project/mocap4ros2_optitrack#1]
I'm looking forward to packages of ROS2 compatible with optitrack.
Is this repo work-in-progress (WIP)?
Is there any timeline or plan?

**Comment by fmrico** [comment]
Hi @JinraeKim 

This repo was created as a response to https://github.com/MOCAP4ROS2-Project/mocap4ros2_core/issues/5 @Chao-Wei94 was interested in it.

Best

**Comment by fmrico** [comment]
Hi @ljaniec 

I hope so. This summer we plan to move to humble all the software in the lab.

If you want to contribute, I can create a `humble-devel `branch to start working

Best
Francisco

**Comment by ljaniec** [comment]
I can try to prepare a first draft in a few days, up to 2 weeks I think :) I will ping you there when it will be ready to check

**Comment by fmrico** [comment]
> I can try to prepare a first draft in a few days, up to 2 weeks I think :) I will ping you there when it will be ready to check.

Excellent

> EDIT: Since Foxy usual naming is not `<ros-version>-devel`, but `galactic`/`humble` etc.

Good to know. I will try to follow the convention in new branches
