### ISSUE TITLE
Small error in the included file  `gt_component.cpp` in the `mocap_robot_gt` 

### ISSUE THREAD

**Issue by ljaniec** [MOCAP4ROS2-Project/mocap4ros2_optitrack#11]
I had to change this line in the `gt_component.cpp` in the `mocap_robot_gt` to build it successfully:

- from:

```
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
```

- to:

```
`#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
```

**Comment by fmrico** [comment]
Hi @ljaniec 

What distro are you using? The last works, including many refactoring PRs, assume you are working with `humble`. The issue you are describing is related to this, probably.

As soon as we stabilize all, probably in few weeks (as soon as we fix CI and some details), I will start creating `<distro>-devel`  branches, create packages for all, and it will be more evident the working distro. Commonly, `main` branches point to the last available distro (`rolling` or `humble`).

Thanks!!

**Comment by ljaniec** [comment]
Hello,

At the moment I am on ROS 2 Galactic, but I can also check this with ROS 2 Humble - there are some packages within `ecl_core` that do not compile for Turtlebot2 in Ubuntu 22.04 and I need to take a step back with the lab software upgrade to the older distro, ROS 2 Galactic with Ubuntu 20.04.

Another possible problem for us to test and use this software is a really old version of Motive Track in the laboratory - we have 2014 version 1.72 with NatNet 2.7 (no backward compatibility with NatNet 3.0), which can be connected via NatNet SDK SampleClient as legacy server, but any ROS2 MoCap package will not work without debugging problems.

![image](https://user-images.githubusercontent.com/11331846/179566269-c6492e68-5ed0-497c-84c0-d53f04b337a7.png)

![image](https://user-images.githubusercontent.com/11331846/179566044-a59e8099-5300-4668-becf-c66781c97d20.png)


You can suggest the best option to solve these problems, I'd love to hear it.

Best,
Łukasz Janiec

**Comment by fmrico** [comment]
Hi @ljaniec 

The first problem does not seem hard to solve (waiting for ecl, or hack by yourself). The second problem seems not so easy...

Best
