### ISSUE TITLE
fatal error: NatNetTypes.h: No such file or directory

### ISSUE THREAD

**Issue by sytnocui** [MOCAP4ROS2-Project/mocap4ros2_optitrack#16]
if somebody do not install  NatNetSDK , 

when run:
colcon build --symlink-install

it will report a error:

fatal error: NatNetTypes.h: No such file or directory

So,it is better for you to add a step in the begining of README to remind people to install NatNetSDK
(website:  https://optitrack.com/support/downloads/developer-tools.html#natnet-sdk)
Thanks

**Comment by aarsht7** [comment]
@sytnocui  It is required to be connected to the internet while building the package for the first time. If anything is missing, [this file](https://github.com/MOCAP4ROS2-Project/mocap4ros2_optitrack/blob/main/mocap_optitrack_driver/install_sdk.py) should download the required material at required place while building the package.

**Comment by sytnocui** [comment]
Well, maybe , because I am in China, there are some network problems. The install_sdk.py do not run well. I have tried to run the script manually, but python give me a HttpNotconnectError, although I run it with a VPN. 

Finally, I manually download NatNetSDK and p it into the correct folder. Everything work well.

**Comment by fmrico** [comment]
Excellent!! 👏👏

Closing issue then
