### ISSUE TITLE
Connected but no rigid body or other data being published. 

### ISSUE THREAD

**Issue by joestg** [MOCAP4ROS2-Project/mocap4ros2_optitrack#18]
I have a ubuntu 22.04 system with ROS2 humble. I run the code and it connects successfully showing motive version and FPS. I activate it and launch RVIZ. I don't see any data. When I echo /rigidbodies /markers I do not see any messages. 

I have the parameters set to
"Multicast"
IP's are set x.x.5.74  &  x.x.4.234. Not sure if the sub net matters?
Rigid_body_name="wand" and I have a "wand" setup in Motive

Application: Motive (ver. 3.0.3.1)
NatNet Version: 4.0.0.0
Mocap Framerate : 120.00 (updates based off motive)
Connected!
Activated!

I do not see any rigid body or marker data but the Frame rate and other items seem to work.

**Comment by joestg** [comment]
It was the sub net mismatch I believe. When I connected directly through a passive switch with static IPs it worked. Is there anyway to change the subnet mask to 255.255.0.0 ?

**Comment by xaxam2001** [comment]
I have an issue that looks similar.

I'm using ROS2 Galactic on Ubuntu 20.04 and when I launch the optitrack2.launch.py launch file it connects successfully giving me the NatNet version, the IP addresses and the frame rate. But when I'm trying to listen to the topic /rigid_bodies or any other topic, nothing seems to be published. I tried both Unicast and Multicast configuration it did not change anything and I have the same submask 255.255.0.0 on both computer.

Here is the info logs of the optitrack2.launch.py from mocap_optitrack_driver package:
```
[mocap_optitrack_driver_main-1] [INFO] [1686900523.648251036] [mocap_optitrack_driver_node]: Trying to connect to Optitrack NatNET SDK at X.X.2.121 ...
[mocap_optitrack_driver_main-1] [INFO] [1686900523.670393204] [mocap_optitrack_driver_node]: ... connected!
[mocap_optitrack_driver_main-1] [INFO] [1686900523.673155282] [mocap_optitrack_driver_node]: 
[mocap_optitrack_driver_main-1] [Client] Server application info:
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.673241751] [mocap_optitrack_driver_node]: Application: Motive (ver. 2.1.0.0)
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.673280439] [mocap_optitrack_driver_node]: NatNet Version: 3.1.0.0
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.673298681] [mocap_optitrack_driver_node]: Client IP:X.X.2.143
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.673312550] [mocap_optitrack_driver_node]: Server IP:X.X.2.121
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.673324022] [mocap_optitrack_driver_node]: Server Name:
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.675765423] [mocap_optitrack_driver_node]: Mocap Framerate : 120.00
[mocap_optitrack_driver_main-1] 
[mocap_optitrack_driver_main-1] [INFO] [1686900523.675852398] [mocap_optitrack_driver_node]: Configured!
[mocap_optitrack_driver_main-1] 
```

**Comment by aarsht7** [comment]
@joestg @xaxam2001 , I am not sure but can you try disabling the firewall on windows for the connected local network?

I faced similar issue with ros1 and disabling firewall helped to solve the issue.

**Comment by xaxam2001** [comment]
@aarsht7 , If I really do not find any other solution, I will ask if I can disable the firewall (because I do not have administrator's rights on the motion capture computer). But I am not sure that disabling the windows firewall will resolve the issue because someone who is using the package told me that everything was working fine for him (with the same windows computer, so with the same firewall). So, I think it may be a configuration problem on one of the two computers.

**Comment by xaxam2001** [comment]
Update:
I do not know if it was normal, but the following lines were commented in the launch file:
```py
    # Make the driver node take the 'activate' transition
    driver_activate_trans_event = EmitEvent(
       event = ChangeState(
           lifecycle_node_matcher = launch.events.matchers.matches_action(driver_node),
           transition_id = lifecycle_msgs.msg.Transition.TRANSITION_ACTIVATE,
        )
    )
    
    [...]
    
    ld.add_action(driver_activate_trans_event)
```

Unfortunately, I uncommented them and, apart from an `Activated!` message in the logs, the topics are still empty. Maybe I need to change something else or do I need to leave this lines commented?

**Comment by xaxam2001** [comment]
I find a solution for me. After that I uncomment the lines in my previous comment above, I just switch back to Unicast an now it works fine.

**Comment by joestg** [comment]
I found I could run multicast using a manual static IP configuration. 
I found I could run Unicast over wifi using DHCP.

**Comment by maxpolzin** [comment]
I am encountering the same error on Ubuntu 22.04 with the current main branch. I receive neither /markers nor /rigid_bodies.

For our [ROSbloX](https://rosblox.github.io/ ), we are using these versions of the packages: https://github.com/rosblox/ros-mocap4ros2-optitrack and they work fine for us atm.

Plus: The forked https://github.com/rosblox/mocap4ros2_optitrack/ package in there implements delay compensation in the timestamp if your Optitrack cameras provide it.

**Comment by fmrico** [comment]
I think we can close this. My comments about direct activation are in #22 . I prefer a parameter instead of directly activation in the launcher. The connection errors are not an issue of this repo.

Reopen if you disagree, please, and we can discuss it.
