### ISSUE TITLE
Has anyone been able to get streaming to work with Humble and Motive?

### ISSUE THREAD

**Issue by andrewyarovoi** [MOCAP4ROS2-Project/mocap4ros2_optitrack#20]
I recently tried streaming from the latest version of Motive (running on Windows) to the Ubuntu laptop setup with Humble. I've checked that I can ping the other computer. I've also connected both computers to the same router and disabled the firewall on the Windows machine. I matched the local interface address in Motive and the server address in the mocap_optitrack_driver_params.yaml to the windows ip address. I've also ensured all the multicast settings match. When I launch the node, it quickly states `... not connected :(`. What am I doing wrong (or how can I determine why it is not connecting)?

**Comment by fmrico** [comment]
I will try it the next week. Let's see if something is broken....

**Comment by andrewyarovoi** [comment]
Thank you for offering your help. I really appreciate the support. After a lot of frustration, it turned out to be a networking issue where the companies software was blocking the messages, even when the firewall is disabled. I can confirm that the node works perfectly on humble
