### ISSUE TITLE
Marker Topics Not Being Updated

### ISSUE THREAD

**Issue by TimJDix** [MOCAP4ROS2-Project/mocap4ros2_optitrack#27]
The client successfully connected to the mocap server without issue, but when I echo the /markers or /rigid_bodies topics they're both empty, nothing's being published to them.
In our ROS1 setup, we had to configure rigid bodies and streaming IDs in the .yaml file. I'm assuming something similar has to be done for ROS2, but I can't find any documentation on how to do this in proper syntax.

**Comment by fmrico** [comment]
Is your driver activated?

```
ros2 lifecycle set /mocap_optitrack_driver_node activate
```

**Comment by aarsht7** [comment]
> In our ROS1 setup, we had to configure rigid bodies and streaming IDs in the .yaml file.

Rigidbodies and markers are identified automatically. You do not need any extra files to mention the id and names of the rigid body.

**Comment by TimJDix** [comment]
> Is your driver activated?
When I try to run that command, I get "Node not found"

**Comment by TimJDix** [comment]
> Is your driver activated?

Yes, driver is successfully activated, connection to server is successful, and the markers show on the serverside mocap window, but nothing seems to be making it to the client.

**Comment by TimJDix** [comment]
> ros2 lifecycle set /mocap_optitrack_driver_node activate

In the mocap4Ros2 documatnation, it says to use:
`ros2 lifecycle set /mocap4r2_optitrack_driver_node activate`

which returns
`Node not found`

But when I use the command you gave me:
`ros2 lifecycle set /mocap_optitrack_driver_node activate`

The transition is successful. Is this an issue? Or a typo in documentation?

**Comment by fmrico** [comment]
We are now transitioning from mocap to mocap4r2. Stay tuned for the new incoming tools to make this easier.

We will update the docs also soon.

Sorry for the inconvenience

**Comment by TimJDix** [comment]
Is there anything else to check to figure out why the markers topic isn't being published to at all, despite a successful connection to the mocap server?

**Comment by TimJDix** [comment]
I think it was an issue with multicast. Changed to unicast, and while there is the issue of only being able to stream data to one other device at a time, atleast it's working now.

**Comment by fmrico** [comment]
Hi @TimJDix 

I am happy to see that you found your problem. We should add warnings for these situations...

Best!!

**Comment by PrakritTyagi** [comment]
I would also like to share my experience.

In my university there are two optitrack setups, one in mechanical department and one in robotics department. The one in robotics department does NOT have the above issue but the one in mechanical department gives me the above issue. Solution was to use unicast when using this package. 

Differences 
Robotics: motive software: Tracker 3.0.3 Final
Mechanical: motive software: Body Unlimited 3.0.3 Final

I can give you more specific info if that would be helpful.

**Comment by fmrico** [comment]
Yes, you can do this by setting up the Network connection. Thanks @PrakritTyagi
