### ISSUE TITLE
ROS2 Dashing Support

### ISSUE THREAD

**Issue by sofiakwok** [MOCAP4ROS2-Project/mocap4ros2_optitrack#30]
Is there any chance that this package could be used with Dashing as well as Humble? Right now when I try to build the package, I get a lot of error messages related to RCLCPP, which seems to have changed significantly between ROS2 versions. 
![Screenshot from 2024-01-30 17-39-15](https://github.com/MOCAP4ROS2-Project/mocap4ros2_optitrack/assets/15254305/c39a5d5d-c0f7-4b41-b510-698f7e6825d7)

**Comment by fmrico** [comment]
Hi @sofiakwok 

There is no plan to have a Dashing version, but the errors seem trivial to fix. Use RCLCPP_INFO macro and change the stream style to printf style. For example:

```
RCLCPP_INFO_STREAM(get_logger(), "System [" << get_name() << "] started with topics:");
```
to
```
RCLCPP_INFO(get_logger(), "System %s started with topics:", get_name().c_str());
```
and so on

**Comment by sofiakwok** [comment]
I've managed to get a version of this successfully building, thanks!
