### ISSUE TITLE
Can mocap4ros2 be used with Foxy?

### ISSUE THREAD

**Issue by acrypticcode** [MOCAP4ROS2-Project/mocap4ros2_optitrack#33]
I have a robot that I want to communicate with that only supports ROS 2 Foxy, not Humble or later versions, due to its older Ubuntu OS. This robot needs to receive data from an Optitrack system. I tried to install mocap4ros2 on a Foxy docker container on my PC to test the compatibility and received these errors during installation. I was following the instructions at  `https://github.com/MOCAP4ROS2-Project/mocap4ros2_optitrack` in the readme file. 

This is the partial output to `docker run --net=host -it --rm -v ~/docker-workspaces-cf/mocap4r2_ws:/home/user/ros_ws custom-foxy:latest bash`
![image](https://github.com/MOCAP4ROS2-Project/mocap4ros2_optitrack/assets/156528396/8c118caf-1642-42d5-bf15-68d81123ec5f)

And this is the complete output to `/home/user/ros_ws/src# vcs import < mocap4ros2_optitrack/dependency_repos.repos`
![image](https://github.com/MOCAP4ROS2-Project/mocap4ros2_optitrack/assets/156528396/22ae7513-0a18-44a8-9e9e-3de8a4d27f59)

Is there a way in which this project can be run on Foxy successfully, or do I need to look elsewhere for Optitrack to Foxy translation?

**Comment by aarsht7** [comment]
@acrypticcode , 
You can try changing `.hpp` to `.h` (for all the ros-msg/srv/action related includes in the pkg)

Also, avoid using images in the issue and use copy-paste from terminal to make it easier for us to reuse the error msg.
Thanks.

**Comment by fmrico** [comment]
Hi @acrypticcode 

I assume the reply from @aarsht7 solved your problem, so I am closing this issue. Please reopen otherwise.
