### ISSUE TITLE
device_control_msgs missing

### ISSUE THREAD

**Issue by igrak34** [MOCAP4ROS2-Project/mocap4ros2_optitrack#6]
Hello!

I just started developing the galactic version of MoCap, but I encountered dependency issue. 

During the build I got error:
```
Could not find a package configuration file provided by
  "device_control_msgs" with any of the following names:

    device_control_msgsConfig.cmake
    device_control_msgs-config.cmake
```

I couldn't resolve it with rosdep. How can I install missing dependency?

**Comment by aarsht7** [comment]
It is not yet available on ROS index. It is a private archived(I don't know why) repo of this project so you might not be able to access it.

**Comment by fmrico** [comment]
Hi all,

device_control has been renamed to mocap_control, and moved to https://github.com/MOCAP4ROS2-Project/mocap/tree/main/mocap_control
